import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ChevronLeft, ChevronRight, CirclePlus, ClipboardCheck, ExternalLink, LayoutDashboard, ShieldAlert, TrendingUp, UsersRound } from 'lucide-react'
import SectionHeader from '../components/SectionHeader'
import StatusPill from '../components/StatusPill'
import GrowthFunnelBoard from '../components/GrowthFunnelBoard'
import MarketKOLBoard from '../components/MarketKOLBoard'
import AttributionExperimentBoard from '../components/AttributionExperimentBoard'

const connectionTones = { '已连接': 'positive', '待授权': 'warning', 'Token 即将过期': 'warning', '数据异常': 'negative' }

function formatCompact(value) {
  return value >= 1000000 ? `${(value / 1000000).toFixed(2)}M` : value >= 1000 ? `${Math.round(value / 1000)}K` : `${value}`
}

function Sparkline({ values, color = '#5b936e' }) {
  const points = values.map((value, index) => `${(index / Math.max(values.length - 1, 1)) * 100},${100 - value}`).join(' ')
  return <svg className="dashboard-sparkline" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="近 7 日趋势"><polyline points={points} fill="none" stroke={color} strokeWidth="3" vectorEffect="non-scaling-stroke" /></svg>
}

export default function Dashboard({ accounts = [], candidateCount, assets = [], leaderTasks = [], activity = [], onOpenAccount, onDemoAction }) {
  const [railCollapsed, setRailCollapsed] = useState(() => window.localStorage.getItem('growth-dashboard-rail') === 'collapsed')
  const [statusFilter, setStatusFilter] = useState('全部')
  const [categoryFilter, setCategoryFilter] = useState('全部')
  useEffect(() => { window.localStorage.setItem('growth-dashboard-rail', railCollapsed ? 'collapsed' : 'expanded') }, [railCollapsed])
  const portfolio = useMemo(() => {
    const metrics = accounts.map((account, index) => account.metrics || { impressions: [842000, 516000, 482000][index] || 0, likeRate: [6.4, 4.2, 6.5][index] || 0, engagementRate: [7.8, 4.9, 7.7][index] || 0, posts: [5, 3, 4][index] || 0, connectionStatus: ['已连接', '数据异常', '待授权'][index] || '待授权', trend: [[58, 63, 60, 72, 68, 81, 86], [71, 68, 64, 57, 53, 48, 45], [54, 57, 62, 65, 67, 70, 74]][index] || [] })
    const totals = metrics.reduce((sum, item) => ({ impressions: sum.impressions + item.impressions, posts: sum.posts + item.posts, likeRate: sum.likeRate + item.likeRate, engagementRate: sum.engagementRate + item.engagementRate }), { impressions: 0, posts: 0, likeRate: 0, engagementRate: 0 })
    const count = Math.max(accounts.length, 1)
    const trend = Array.from({ length: 7 }, (_, index) => Math.round(metrics.reduce((sum, item) => sum + (item.trend[index] || 0), 0) / count))
    return { metrics, totals: { ...totals, likeRate: (totals.likeRate / count).toFixed(1), engagementRate: (totals.engagementRate / count).toFixed(1) }, trend }
  }, [accounts])
  const visibleAccounts = accounts.filter((account, index) => (statusFilter === '全部' || portfolio.metrics[index].connectionStatus === statusFilter) && (categoryFilter === '全部' || account.categoryLabel === categoryFilter))
  const openTasks = leaderTasks.filter((task) => task.status !== '已完成')
  const reviewCount = assets.filter((asset) => asset.status === '待审核').length
  const riskAccounts = accounts.filter((account) => account.health < 70)
  const healthCounts = { healthy: accounts.filter((account) => account.health >= 80).length, attention: accounts.filter((account) => account.health >= 70 && account.health < 80).length, risk: riskAccounts.length }

  return <div className={`page-content page-dashboard ${railCollapsed ? 'dashboard-rail-collapsed' : ''}`}>
    <div className="dashboard-main">
      <div className="page-hero dashboard-hero"><div><div className="eyebrow"><LayoutDashboard size={14} /> EXECUTIVE OVERVIEW <span className="eyebrow-line" /></div><h1>全部账号，今天发生了什么？</h1><p className="hero-copy">跨账号看增长、内容与风险；需要具体处理时，再下钻进入增长情报驾驶舱。</p></div><div className="hero-actions"><button className="secondary-button" onClick={() => onDemoAction('账号连接为 Demo 状态；真实 X OAuth 需要后续配置开发者凭据。')}><CirclePlus size={15} />添加账号</button><button className="primary-button" onClick={() => onDemoAction('连接 X 为演示入口，不会发起真实授权。')}><ExternalLink size={15} />连接 X</button></div></div>

      <div className="portfolio-summary"><div><span>管理账号</span><strong>{accounts.length.toString().padStart(2, '0')}</strong><small>{portfolio.metrics.filter((item) => item.connectionStatus === '已连接').length} 已连接</small></div><div><span>总曝光</span><strong>{formatCompact(portfolio.totals.impressions)}</strong><small className="positive-copy">+18.6% vs. last week</small></div><div><span>平均点赞率</span><strong>{portfolio.totals.likeRate}%</strong><small className="positive-copy">+0.8pt</small></div><div><span>平均互动率</span><strong>{portfolio.totals.engagementRate}%</strong><small>评论 / 收藏综合</small></div><div><span>待处理</span><strong>{`${openTasks.length + riskAccounts.length}`.padStart(2, '0')}</strong><small className="risk-copy">风险 / Leader 任务</small></div></div>

      <section className="section-block dashboard-surface decision-today"><SectionHeader eyebrow="TODAY · DECISION BRIEF" title="今天，增长应该先做什么？" detail="从增长现象追溯原因，将判断转化为任务，并用实验验证下一步投入。" /><div className="decision-conclusion"><strong>本周核心问题：内容触达较好，但从访问到首次激活存在明显损耗。</strong><span>建议优先优化首次体验 CTA 和落地页路径。</span></div><div className="decision-cards"><article><b>增长机会</b><strong>{candidateCount} 条候选内容</strong><span>筛选高匹配、低风险内容进入小样本测试</span><em>负责人：增长运营 · 截止：本周五 · 指标：有效互动率</em></article><article><b>经营风险</b><strong>{riskAccounts.length} 个账号需关注</strong><span>健康度与评论质量需要优先处理</span><em>负责人：账号运营 · 截止：今日 · 指标：风险关闭率</em></article><article><b>执行任务</b><strong>{openTasks.length} 项待执行</strong><span>将已确认判断推进到发布和复盘</span><em>负责人：内容团队 · 截止：本周 · 指标：按时完成率</em></article><article><b>实验状态</b><strong>3 个进行中</strong><span>验证 CTA 与自然增长是否成立</span><em>护栏：目标用户评论占比 ≥ 60%</em></article></div></section>
      <GrowthFunnelBoard />
      <MarketKOLBoard />
      <AttributionExperimentBoard assets={assets} />

      <div className="dashboard-grid-top"><section className="section-block dashboard-surface trend-surface"><SectionHeader eyebrow="01 · PORTFOLIO TREND" title="近 7 日账号组合表现" detail="曝光与互动趋势用于判断整体经营是否健康。" action={<span className="queue-count">7 days</span>} /><div className="trend-plot"><Sparkline values={portfolio.trend} /><div className="trend-axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="trend-legend"><span><i className="legend-dot legend-green" />曝光趋势</span><span><i className="legend-dot legend-blue" />互动趋势</span><strong>组合健康度 {Math.round(accounts.reduce((sum, account) => sum + account.health, 0) / Math.max(accounts.length, 1))}/100</strong></div></section><section className="section-block dashboard-surface funnel-surface"><SectionHeader eyebrow="02 · CONTENT FUNNEL" title="内容经营漏斗" detail="从机会发现到进入审核的转化。" /><div className="funnel-stack"><div style={{ width: '100%' }}><span>热点发现</span><b>{String(12).padStart(2, '0')}</b></div><div style={{ width: '83%' }}><span>候选内容</span><b>{String(candidateCount).padStart(2, '0')}</b></div><div style={{ width: '62%' }}><span>内容资产</span><b>{String(assets.length).padStart(2, '0')}</b></div><div style={{ width: '43%' }}><span>待审核</span><b>{String(reviewCount).padStart(2, '0')}</b></div></div></section></div>

      <section className="section-block dashboard-surface account-table-surface"><SectionHeader eyebrow="03 · ACCOUNT MANAGEMENT" title="账号数据看板" detail="连接状态仅用于 Demo 展示；点击账号进入对应的经营驾驶舱。" action={<div className="filter-bar"><select className="category-select" value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)} aria-label="账号分类筛选"><option>全部</option><option>生活方式</option><option>美食餐饮</option><option>旅行户外</option></select>{['全部', '已连接', '待授权', '数据异常'].map((item) => <button key={item} className={statusFilter === item ? 'filter-active' : ''} onClick={() => setStatusFilter(item)}>{item}</button>)}</div>} /><div className="account-table"><div className="account-table-head"><span>账号</span><span>分类</span><span>曝光</span><span>点赞率</span><span>互动率</span><span>近 7 日发帖</span><span>连接状态</span><span /></div>{visibleAccounts.map((account) => { const originalIndex = accounts.findIndex((item) => item.id === account.id); const metrics = portfolio.metrics[originalIndex]; return <button className="account-table-row" key={account.id} onClick={() => onOpenAccount(account.id)}><span className="account-table-name"><i>{account.avatar}</i><span><strong>{account.name}</strong><small>{account.handle}</small></span></span><span><span className="category-chip">{account.categoryLabel}</span></span><span>{formatCompact(metrics.impressions)}</span><span>{metrics.likeRate}%</span><span>{metrics.engagementRate}%</span><span>{String(metrics.posts).padStart(2, '0')}</span><span><StatusPill tone={connectionTones[metrics.connectionStatus] || 'neutral'}>{metrics.connectionStatus}</StatusPill></span><span><ChevronRight size={15} /></span></button> })}{visibleAccounts.length === 0 && <div className="table-empty">当前筛选没有账号。</div>}</div></section>

      <div className="dashboard-grid-bottom"><section className="section-block dashboard-surface health-distribution"><SectionHeader eyebrow="04 · HEALTH DISTRIBUTION" title="账号健康分布" /><div className="health-donut"><div><strong>{Math.round(accounts.reduce((sum, account) => sum + account.health, 0) / Math.max(accounts.length, 1))}</strong><small>/100</small></div></div><div className="health-key"><span><i className="legend-dot legend-green" />健康 {healthCounts.healthy}</span><span><i className="legend-dot legend-gold" />关注 {healthCounts.attention}</span><span><i className="legend-dot legend-red" />风险 {healthCounts.risk}</span></div></section><section className="section-block dashboard-surface action-summary"><SectionHeader eyebrow="05 · PRIORITY SUMMARY" title="今天的经营判断" /><div className="priority-summary-row"><AlertTriangle size={17} /><span><strong>{riskAccounts[0]?.name || '暂无风险账号'}</strong>{riskAccounts.length ? ' 的互动与评论意图需要优先处理。' : ' 当前没有账号级风险。'}</span></div><div className="priority-summary-row"><ClipboardCheck size={17} /><span><strong>{openTasks.length} 项 Leader 任务</strong>等待负责人执行与下次日报验证。</span></div><div className="priority-summary-row"><TrendingUp size={17} /><span><strong>{candidateCount} 条候选内容</strong>可进入爆款拆解和二创。</span></div></section></div>
    </div>

    <aside className="operating-rail"><button className="rail-toggle" onClick={() => setRailCollapsed((current) => !current)} aria-label={railCollapsed ? '展开经营侧栏' : '收起经营侧栏'}>{railCollapsed ? <ChevronLeft size={16} /> : <ChevronRight size={16} />}</button><div className="rail-collapsed-icons"><ShieldAlert size={16} /><b>{riskAccounts.length}</b><ClipboardCheck size={16} /><b>{openTasks.length}</b></div><div className="rail-expanded"><span className="eyebrow">OPERATING RAIL</span><h3>需要处理</h3><button className="rail-item rail-risk" onClick={() => onOpenAccount(riskAccounts[0]?.id)}><ShieldAlert size={15} /><span><strong>{riskAccounts.length} 个高优风险</strong><small>{riskAccounts[0]?.name || '暂无风险账号'}</small></span></button><button className="rail-item" onClick={() => onDemoAction('请在增长情报的“多账号复盘与 Leader 指导”中处理任务。')}><ClipboardCheck size={15} /><span><strong>{openTasks.length} 项 Leader 待办</strong><small>{openTasks.filter((task) => task.dueDate <= new Date().toISOString().slice(0, 10)).length} 项今日到期</small></span></button><button className="rail-item" onClick={() => onDemoAction('请在分发优化中查看审核队列。')}><UsersRound size={15} /><span><strong>{reviewCount} 条审核队列</strong><small>等待人工确认</small></span></button><div className="rail-activity"><span className="eyebrow">RECENT ACTIVITY</span>{activity.slice(0, 4).map((item) => <p key={`${item.time}-${item.text}`}><time>{item.time}</time>{item.text}</p>)}</div></div></aside>
  </div>
}
